-- HOOPIQ SUPABASE SETUP
-- Run this in Supabase SQL Editor.
-- Then create your owner account normally and run the final UPDATE below
-- with your real auth.users UUID.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (char_length(username) between 3 and 20),
  total_score bigint not null default 0,
  games_played integer not null default 0,
  best_score integer not null default 0,
  is_owner boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  mode text not null,
  score integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.user_badges (
  user_id uuid not null references public.profiles(id) on delete cascade,
  badge_id text not null,
  earned_at timestamptz not null default now(),
  primary key(user_id,badge_id)
);

alter table public.profiles enable row level security;
alter table public.game_scores enable row level security;
alter table public.user_badges enable row level security;

create policy "profiles public read" on public.profiles for select using (true);
create policy "users read own scores" on public.game_scores for select using (auth.uid()=user_id);
create policy "users insert own scores" on public.game_scores for insert with check (auth.uid()=user_id);
create policy "users read own badges" on public.user_badges for select using (auth.uid()=user_id);
create policy "users insert own badges" on public.user_badges for insert with check (auth.uid()=user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,username)
  values(new.id, coalesce(new.raw_user_meta_data->>'username','Hooper_'||substr(new.id::text,1,6)));
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.increment_profile_stats(p_score integer,p_games integer,p_best integer)
returns void language sql security definer set search_path=public as $$
 update public.profiles
 set total_score=total_score+p_score,
     games_played=games_played+p_games,
     best_score=greatest(best_score,p_best)
 where id=auth.uid();
$$;

-- Leaderboard view: daily / weekly / alltime.
create or replace view public.leaderboard_scores as
select p.username,
       case
         when gs.created_at >= date_trunc('day',now()) then 'daily'
         when gs.created_at >= date_trunc('week',now()) then 'weekly'
         else 'alltime'
       end as period,
       sum(gs.score)::bigint as score
from public.game_scores gs
join public.profiles p on p.id=gs.user_id
group by p.username, period;

-- IMPORTANT: after creating your own account, get your UUID from
-- Authentication > Users and run:
-- update public.profiles set is_owner=true where id='YOUR-UUID-HERE';

-- For stronger production security, keep the owner column write-protected
-- and never expose a Supabase service_role key in the website.
